#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 21 08:23:22 2021

@author: macbookpro
"""
#reading from url and getting ages>=50
import requests
import numpy as np
import pandas as pd
import json

r = requests.get('https://coderbyte.com/api/challenges/json/age-counting')
data= ((r.json()['data']))
c=0

# data = data.split('age'

data = data.replace(" ","")
string = data.split(',')
age = string[1::2]

age=age[:5]
print(age)
for value in age:
    value=value.split('=')
    if int(value[1])>=50:
        c=c+1
    
print (c)

# # res = json.loads(age)
